# Generated by Django 5.2.3 on 2025-07-01 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=255)),
                ('section', models.CharField(max_length=255)),
                ('sub_section', models.CharField(max_length=255)),
                ('comments', models.TextField()),
                ('SME', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='online_help.user')),
            ],
        ),
        migrations.CreateModel(
            name='MajorDocu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects', models.CharField(max_length=255)),
                ('SME', models.CharField(max_length=255)),
                ('support', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supported_docs', to='online_help.user')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_docs', to='online_help.user')),
            ],
        ),
        migrations.CreateModel(
            name='TaskWriter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_help.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_help.user')),
            ],
            options={
                'unique_together': {('task', 'user')},
            },
        ),
    ]
