# Generated by Django 5.2.3 on 2025-07-07 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_help', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion',
            field=models.CharField(default='0%', max_length=100),
        ),
    ]
