# Generated by Django 5.2.3 on 2025-07-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_help', '0005_alter_task_sme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='SME',
            field=models.CharField(default=3, max_length=255),
            preserve_default=False,
        ),
    ]
