# Generated by Django 5.2.3 on 2025-07-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_help', '0012_alter_task_sme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='SME',
            field=models.CharField(blank=True, default='no sme', max_length=255, null=True),
        ),
    ]
