# Generated by Django 5.2.3 on 2025-07-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_help', '0014_alter_task_sme'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
