# Generated by Django 5.2.3 on 2025-07-21 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_help', '0015_task_modified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_help.document'),
        ),
    ]
