# Generated by Django 5.2.3 on 2025-07-21 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_help', '0016_document_alter_task_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='document',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
